### ISSUE TITLE
There is a Bahn api now

### ISSUE THREAD

**Issue by deisi** [kennell/schiene#16]
https://developer.deutschebahn.com/store/apis/info?name=Timetables&version=v1&provider=DBOpenData

What do you think? It would need registration by everyone who whats to use it, but we would get rid of the html paresing. In terms of stability and future proof ness it would get a lot better I think. For Home-Assistant I think it's the right way.

**Comment by kennell** [comment]
Does this new timetables API contain realtime information on delays? If yes i would go forward to move this library to use the timetable API. If no, its probably best to start a second project and keep this as-is (which should be straightforward since they seem to have a Swagger-compatible API)

**Comment by deisi** [comment]
If I understand the fcgh parameter correctly, it can give real time formation. 

> Implementation Notes
> 
> Returns a Timetable object (see Timetable) that contains all known changes for the station given by evaNo.
> 
> The data includes all known changes from now on until ndefinitely into the future. Once changes become obsolete (because their trip departs from the station) they are removed from this resource.
> 
> Changes may include messages. On event level, they usually contain one or more of the 'changed' attributes ct, cp, cs or cpth. Changes may also include 'planned' attributes if there is no associated planned data for the change (e.g. an unplanned stop or trip).
> 
> Full changes are updated every 30s and should be cached for that period by web caches.

**Comment by deisi** [comment]
Time changes show up with a `ct` label. E.g.

`curl -X GET --header "Accept: application/xml" --header "Authorization: Bearer token_here" "https://api.deutschebahn.com/timetables/v1/fchg/8000240"`

gives amongst others:

``` xml
<timetable station="Mainz Hbf" eva="8000240">
 <s id="4660398913906016542-1802281200-13" eva="8000240">
        <ar ppth="Interlaken Ost|Interlaken West|Spiez|Thun|Bern|Olten|Liestal|Basel SBB|Basel Bad Bf|Freiburg(Breisgau) Hbf|Karlsruhe Hbf|Mannheim Hbf" pp="3a/b" ct="1802281823" pt="1802281718">
              <m id="r26673692" t="d" c="48" ts="1802281349"/>
        </ar>
        <dp ppth="Koblenz Hbf|Bonn Hbf|Köln Hbf|Düsseldorf Hbf|Duisburg Hbf|Essen Hbf|Bochum Hbf|Dortmund Hbf|Münster(Westf)Hbf|Osnabrück Hbf|Diepholz|Bremen Hbf|Hamburg-Harburg|Hamburg Hbf|Hamburg Dammtor|Hamburg-Altona" pp="3a/b" ct="1802281825" pt="1802281720">
              <m id="r26673692" t="d" c="48" ts="1802281349"/>
        </dp>
        <tl f="F" t="p" o="85" c="EC" n="6"/>
  </s>
</timetable>
```

and in there you find: ` ct="1802281823" pt="1802281718"` meaning pt: planned time was 17:18 and then it was ct: chaged time to 18:23. So a minute resolution is provided.

**Comment by kennell** [comment]
Jesus Christ. This XML looks almost as bad as the HTML code.

**Comment by deisi** [comment]
:joy:

**Comment by kennell** [comment]
To answer your original question: i will not be integrating the new timetable API into this project. I will however create a spin-off that uses the timetable API and wrap it a pythonic-way. Will announce and link project once usable version is ready.

**Comment by derhuerst** [comment]
FYI there's also the "mobile" API with `mgate.exe` in the URL. It is the API that the DB app talks to, so it provides realtime data and journey planning.

If you want to cover it in Python, consider porting [hafas-client](https://github.com/public-transport/hafas-client).
