### ISSUE TITLE
"self.data.update & self.only_direct" in update

### ISSUE THREAD

**Issue by DuckY1987** [kennell/schiene#19]
i use this package with home-assistant.

Since i upgraded i have following error:

"/usr/local/lib/python3.5/dist-packages/homeassistant/components/sensor/deutsche_bahn.py", line 82, in update
"/usr/local/lib/python3.5/dist-packages/homeassistant/components/sensor/deutsche_bahn.py", line 105, in update

Here is the same error reported what i had a couple times in log:

https://github.com/home-assistant/home-assistant/issues/21118

self.data.update self.only_direct

Could you please fix it? :-)

Thanks a lot!

**Comment by kennell** [comment]
Duplicate of #18

**Comment by kennell** [comment]
FYI: Fixed in https://github.com/kennell/schiene/pull/20, released on PyPI as version `0.23`
