### ISSUE TITLE
Is there a limit to requests / seconds?

### ISSUE THREAD

**Issue by kevinkit** [kennell/schiene#23]
I am playing with this project and sometimes i get an empty list from the `connections()` function. 

Is this due to requesting too often or due to some other error? Is there a specific limit?

**Comment by kennell** [comment]
I am not aware of any fixed limits.

When you get a empty connection list and do a immediately follow-up request, is it still empty?

**Comment by kevinkit** [comment]
Sorry for the late reply. A followup request stays empty but will Not bei
empty some time (Like an hour or a day later).

I will try to write a script to reproduce the error

Kevin Kennell <notifications@github.com> schrieb am Fr., 31. Jan. 2020,
20:30:
