### ISSUE TITLE
Parallel?

### ISSUE THREAD

**Issue by ChristophGmeiner** [kennell/schiene#24]
Hi there,

great package...it's really helpful.

Do you have any idea how I can do many requests at once?

thanks

**Comment by kennell** [comment]
If you are looking to get multiple connections in one request, that is not possible with this package nor the Fahrplan API i believe.

If you are looking to do bunch of requests in parallel (querying connection per request) i would suggest looking into the usual Python tools, either the `threading` stdlib or something queue-worker based like Celery
