### ISSUE TITLE
schiene crashes

### ISSUE THREAD

**Issue by gpgmailencrypt** [kennell/schiene#29]
Hi, the code crashes when trying to query the next train to Vienna. The 'Wien Hbf' is a valid name for the station as returned by s.stations('Wien')
```
s.connections('München','Wien Hbf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "schiene.py", line 135, in connections
    return parse_connections(rsp.text)
  File "schiene.py", line 35, in parse_connections
    data = parse_delay(data)
  File "schiene.py", line 57, in parse_delay
    delay_departure_raw = soup.find('div', class_="routeStart").find('span', class_=["delay", "delayOnTime"])
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by kennell** [comment]
Hi. I can reproduce and confirm the issue.

Most likely the HTML slightly differs for international connections. Unfortunately i do not have time to investigate this issue in detail any time soon, but i would welcome a pull request on this matter, if you are able to fix it.

**Comment by kennell** [comment]
Fixed in https://github.com/kennell/schiene/pull/30
