### ISSUE TITLE
Not getting the next train correctly

### ISSUE THREAD

**Issue by deisi** [kennell/schiene#3]
Hey

I'm experimenting with your API and in general it is working. However when I make a 

    import schiene
    data = schiene.Schiene()
    res = data.connections('start', 'goal')

call, it returns a list of the next four trains for this connection. I think res[0] should be the next connection, however I usually see tat res[0] is the one after the next, and the next connecton is not
pulled in at all.

**Comment by kennell** [comment]
I can confirm the issue, will look into it.

**Comment by kennell** [comment]
Fixed. Sorry for the long wait.

**Comment by deisi** [comment]
Thanks a lot. I will test at some point in the near future.
